---
# 둘째 날
- 아직 어색하지만 재미있는 파이썬
---

---
# for 문
- 정말정말 많이쓰고
- 한번 이해하면 정말 두고두고 좋은
- 처음 배울 때 아예 체득해야함 !!!!!!
- ---

In [1]:
for i in range(1,6):
    print(123)
    print(456)
    print(789)

123
456
789
123
456
789
123
456
789
123
456
789
123
456
789


In [1]:
for i in range(1,5):
print(i)
    print(i+1) # 줄을 잘 맞춰야 하는 것이 for 문의 기본!

IndentationError: expected an indented block after 'for' statement on line 1 (2842476430.py, line 2)

In [2]:
for i in range(1,5):
    print(i)
print(i+1)

1
2
3
4
5


In [3]:
for i in range(1,5):
    print(i)
    print(i+1)

1
2
2
3
3
4
4
5


In [4]:
for i in [9,8,4,1]:
    print(i)

9
8
4
1


---
list와 range

---

In [5]:
list(range(2,11,2))

[2, 4, 6, 8, 10]

In [6]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
list(range(10,2)) # 10 부터 2 사이는 없겠죠?

[]

In [ ]:
#list(range(stop=10,step=2))

In [8]:
list(range(1,10,2)) # 1부터 10 까지, 2 step씩

[1, 3, 5, 7, 9]

In [9]:
for i in range(2,26,2):
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24


In [10]:
for i in range(-14,-7): # 음수도 가능! 대신 역순으로 생각해야 함
    print(i)

-14
-13
-12
-11
-10
-9
-8


In [11]:
for i in range(-8,-14,-1):
    print(i)

-8
-9
-10
-11
-12
-13


In [13]:
for i in range(8,14):
    print(-i)

-8
-9
-10
-11
-12
-13


In [14]:
for i in range(3,30,3):
    print(i)

3
6
9
12
15
18
21
24
27


In [ ]:
#for i in range(1,6):
#    print('0.')+print(i)

In [15]:
for i in range(1,6,1):
    print(i/10) # 소수점으로 나타내기

0.1
0.2
0.3
0.4
0.5


In [16]:
for i in [0.1,0.2,0.3,0.4,0.5]: # 같은 값을 출력하지만 사용법이 다름
    print(i)

0.1
0.2
0.3
0.4
0.5


In [17]:
x=0
y=0
for i in range(1,101):
    y+=i # 1, 3, 6, ...
    x=i # 1, 2, 3, ...
    if(y>100):
        break # 멈춤
print('정수값'+str(x)+'까지의 합은'+str(y)+'입니다')

정수값14까지의 합은105입니다


In [18]:
for i in range(4,50,4):
    print(i)

4
8
12
16
20
24
28
32
36
40
44
48


In [19]:
# 숫자를 입력 받기
input_number = int(input('숫자를 입력하세요 : '))

In [ ]:
input_number # 4 입력

In [20]:
for i in range(2,input_number+1,2):
    print(i)

2
4


---
while 문

---

In [21]:
ind = 0

while ind < 10:
    print('hello')
    ind += 1

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello


In [22]:
ind=2
while ind < input_number:
    print(ind)
    ind+=2

2


In [23]:
input_number = int(input('숫자 입력 : ')) # 10 입력

In [24]:
start_number = 2

while start_number <=input_number:
    print(start_number)
    
    start_number += 2

2
4
6
8
10


---
- continue
- break
- pass

---

In [25]:
for i in range(1,11):
    print(i)
    continue
    print('-----')

1
2
3
4
5
6
7
8
9
10


In [27]:
for i in range(1,11):
    print(i)
    break
    print('-----')

1


In [28]:
for i in range(1,11):
    print(i)
    pass
    print('-----')

1
-----
2
-----
3
-----
4
-----
5
-----
6
-----
7
-----
8
-----
9
-----
10
-----


In [29]:
ind = 0

while 1:
    print(ind)
    
    ind += 1
    if ind > 10:
        break

0
1
2
3
4
5
6
7
8
9
10


In [30]:
for i in range(1,4):
    print(i)
    
    for j in range(9,6,-1):
        print(j)

1
9
8
7
2
9
8
7
3
9
8
7


In [31]:
i = 0

while i < 3:
    print(i)
    i += 1
    
    j = 5

    while j > 3:
        print(j)
        j -= 1

0
5
4
1
5
4
2
5
4


---
list를 넣어보아요

---

In [32]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]

In [33]:
for i in list1:
    
    print(i,end = "")

[1, 2, 3][4, 5, 6][7, 8, 9]

In [34]:
for i in range(1,10):
    print(i, end='')
    for j in range(3,1,4):
        print('\n')
        j += 3

123456789

In [35]:
list1[1]

[4, 5, 6]

In [36]:
list1[1][2]

6

In [38]:
for i in range(1,10,1):
    list1[i]
    for j in range(1,10,1): # 범위를 벗어나면 에러를 내뱉음
        list1[i][j]

IndexError: list index out of range

In [39]:
for i in list1:
    print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [40]:
for i in list1:
    for j in i:
        print(j, end = '')

123456789

In [41]:
for i in list1:
    for j in i:
        print(j, end = '')
    print()

123
456
789


In [43]:
list2 = [[1,2],[3,4,5,6],[7,8]]

In [44]:
for i in list2:
    for j in i:
        print(j, end ='')
    print()

12
3456
78


In [45]:
i=1
j=1
while i < 10:
    print(i, end = '')
    i += 1
    while j == i:
        print(j)
        j += 1
    print()

1
2
3
4
5
6
7
8
9


---
if 문

---

In [50]:
x = 1234

In [47]:
x = 123
if x == 123:
    print('x는 123입니다')

x는 123입니다


In [48]:
x = 1234
if x == 123:
    print('x는 123입니다')
    
elif x == 1234:
    print('아님! x는 1234야')

아님! x는 1234야


In [49]:
x = 12345
if x == 123:
    print('x는 123입니다')
    
elif x == 1234:
    print('아님! x는 1234야')
else:
    print('둘다 아니야')

둘다 아니야


In [51]:
a = 99
b = 88

In [52]:
if a == 99 and b == 88:
    print('99와 88이 있어요')

99와 88이 있어요


In [53]:
if a == 99 or b == 88:
    print('둘 중에 무언가는 88이네요')

둘 중에 무언가는 88이네요


In [54]:
if not a == 100:
    print('100')

100


In [55]:
input_number = int(input('숫자 입력 : ')) # 100 입력

In [56]:
if input_number % 2 == 0 :
     print(input_number*(input_number-1))

9900


In [57]:
x = 1
for i in range(1,6):
    x *= i

In [58]:
x

120

---
팩토리얼 만들기

---

In [59]:
y = int(input('1 이상의 자연수를 하나 입력해주세요 : ')) # 30 입력
for i in range(2, y+1, 2):
    x = 1
    for j in range(1, i+1):
        x *= j
    print(f'{i}!의 값은 {x}입니다')

2!의 값은 2입니다
4!의 값은 24입니다
6!의 값은 720입니다
8!의 값은 40320입니다
10!의 값은 3628800입니다
12!의 값은 479001600입니다
14!의 값은 87178291200입니다
16!의 값은 20922789888000입니다
18!의 값은 6402373705728000입니다
20!의 값은 2432902008176640000입니다
22!의 값은 1124000727777607680000입니다
24!의 값은 620448401733239439360000입니다
26!의 값은 403291461126605635584000000입니다
28!의 값은 304888344611713860501504000000입니다
30!의 값은 265252859812191058636308480000000입니다


In [60]:
def func2(i):
    print('안녕')
    print(i)
    print('안녕')
    
for i in range(5):
    func2(i)

안녕
0
안녕
안녕
1
안녕
안녕
2
안녕
안녕
3
안녕
안녕
4
안녕


---
포맷팅

---

In [61]:
x =123
y =45.67
z = ['a']

In [64]:
print("x는 ",x, "y는 ",y,"z는",z,"입니다")

x는  123 y는  45.67 z는 ['a'] 입니다


In [63]:
print("x는 %d이고, y는 %.2f이고, z는 %s입니다" % (x,y,z))

x는 123이고, y는 45.67이고, z는 ['a']입니다


In [65]:
print("x는 {}이고, y는 {}".format(x,y))

x는 123이고, y는 45.67


In [66]:
print(f"x는 {x}이고, y는 {y}이고, z는 {z} 입니다")

x는 123이고, y는 45.67이고, z는 ['a'] 입니다


In [67]:
print("x는 %d, y는 %f" % (x,y))
print("x는 %d, y는 %.3f" % (x,y))

x는 123, y는 45.670000
x는 123, y는 45.670


---
numpy

---

In [68]:
import numpy as np

In [69]:
arr = np.array([1,2,3,4,5])

In [70]:
type(arr)

numpy.ndarray

In [71]:
arr[2]

3

In [72]:
arr[1:5]

array([2, 3, 4, 5])

In [73]:
arr*4

array([ 4,  8, 12, 16, 20])

In [74]:
arr2 =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3 =np.array([5,6,7])

In [75]:
arr2.dot(arr3)

array([ 38,  92, 146])

In [76]:
arr3.dot(arr2)

array([ 78,  96, 114])

In [77]:
list1 = [1,2,3,4,5,6,7,8,9,0]

In [78]:
list1[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [79]:
list1[1:5:2]

[2, 4]

In [80]:
list1[-4]

7

In [81]:
list1[-4:]

[7, 8, 9, 0]

In [82]:
list1[-4::-1]

[7, 6, 5, 4, 3, 2, 1]

In [83]:
list1[::-1]

[0, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [84]:
list1[-4::-3]

[7, 4, 1]

In [85]:
np.save('./f1.npy',arr)

In [ ]:
np.save('c:/users/f2.npy',arr)

In [ ]:
np.load('./f1.npy')

In [ ]:
np.savez('./f1.npz',A = arr)

In [ ]:
np.load('./f1.npz')

In [ ]:
np.load('./f1.npz')['A']

---
pandas

---

In [86]:
import pandas as pd

In [87]:
pd.DataFrame([1,2,3,4,5])

0
0  1
1  2
2  3
3  4
4  5

In [88]:
pd.DataFrame([[1, 2, 3, 4, 5]])

0  1  2  3  4
0  1  2  3  4  5

In [89]:
df = pd.DataFrame([[1,2,3,4,5],[6,7,8,9,0],[6,7,3,5,7]])

In [90]:
df

0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0
2  6  7  3  5  7

In [91]:
df[1][0]

2

In [92]:
df.loc[1]

0    6
1    7
2    8
3    9
4    0
Name: 1, dtype: int64

In [93]:
df.loc[1][0]

6

In [94]:
df.loc[1,0]

6

In [95]:
df.loc[:,1:3]

1  2  3
0  2  3  4
1  7  8  9
2  7  3  5

In [96]:
df.iloc[:,1:3]

1  2
0  2  3
1  7  8
2  7  3

In [97]:
df.columns = ['a','b','c','d','e']
df.index = ['ㄱ','ㄴ','ㄷ']

In [98]:
df

a  b  c  d  e
ㄱ  1  2  3  4  5
ㄴ  6  7  8  9  0
ㄷ  6  7  3  5  7

In [ ]:
df.loc[1:2] # DataFrame에서는 loc 인덱서를 사용할 때 숫자로 된 인덱스가 아니라 인덱스 라벨을 사용
# 이 코드는 엄청나게 긴 오류를 내뱉습니다...^ ^ !

In [107]:
df.iloc[:,1:3] # 정신건강을 위해 정수 인덱스 기능을 하는 iloc를 사용합시다

b  c
ㄱ  2  3
ㄴ  7  8
ㄷ  7  3

In [108]:
df*4

a   b   c   d   e
ㄱ   4   8  12  16  20
ㄴ  24  28  32  36   0
ㄷ  24  28  12  20  28

In [ ]:
df.to_csv('c:/users/f2.csv')

In [ ]:
pd.read_csv('./df.csv')

In [ ]:
pd.read_csv('./df.csv',index_col=0)

In [ ]:
pd.read_csv('./df.csv',index_col=0, header =2)

In [ ]:
df.to_csv('c:/users/f2.csv', index = False)

In [ ]:
pd.read_csv('./df.csv')

In [ ]:
df.to_excel('./df.xlsx')

In [ ]:
pd.read_excel('./df.xlsx')

---
- 함수 맛보기,
- print의 속성
---

In [109]:
1+1

2

In [110]:
print(1+1)

2


In [111]:
a = 1+1

In [112]:
b = print(1+1)

2


In [113]:
a

2

In [114]:
b

In [115]:
type(b)

NoneType

In [116]:
def fn(x):
    return x + 10

In [117]:
fn(10)

20

In [118]:
def fn1(x):
    return x + 10
    return x * 2

In [119]:
fn1(10)

20

In [120]:
def fn2(x):
    if x % 2 == 0:
        return x + 10
    
    return x * 2

In [121]:
fn2(10)

20

In [122]:
fn2(11)

22

In [123]:
def fn3(x):
    return x + 10, x * 2

In [124]:
fn3(15)

(25, 30)

In [125]:
a, b=fn3(15)

In [126]:
a

25

In [127]:
b

30

In [128]:
import time

print("Start")
time.sleep(5)  # 프로그램 실행을 5초 동안 멈춤
print("End")

Start
End
